baseurl = "https://kuikstart.netlify.app/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "anatole"
summarylength = 10
enableEmoji = true

[params]
title = "another FCSci"
author = "IKHLEF Ali"
description = "It's a kuikstart"
profilePicture = "images/profile.jpg"



## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/151ali/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/151ali/"

[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"